### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/scy/money/R$layout;

### ISSUE THREAD

**Issue by richfuns** [NicoToast/fat-aar#1]
hi, everyone
I got a strange issue. When I tried to call and test my aar file in other demo project, it occurs below error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/scy/money/R$layout;
        at com.scy.money.util.ToastUtil.<init>(ToastUtil.java:24)
        at com.scy.money.util.ToastUtil.getToastEmail(ToastUtil.java:31)
        at com.scy.money.model.AppCrashHandler$1.run(AppCrashHandler.java:73)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.scy.money.R$layout" on path: DexPathList[[zip file "/data/app/demo.test.thirdpartapkusingaar-2/base.apk"],nativeLibraryDirectories=[/data/app/demo.test.thirdpartapkusingaar-2/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 3 more`

Anyone knows where the problem are? 
Thanks in advance.

**Comment by NicoToast** [comment]
I think it has to do with proguard-rules.
Try to add
-keep class **.R$* {
 *;
}

**Comment by anshul-arora** [comment]
I am getting similar issue. I haven't used any Proguard rules

**Comment by NicoToast** [comment]
> hi, everyone
> I got a strange issue. When I tried to call and test my aar file in other demo project, it occurs below error:
> 
> `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/scy/money/R$layout; at com.scy.money.util.ToastUtil.<init>(ToastUtil.java:24) at com.scy.money.util.ToastUtil.getToastEmail(ToastUtil.java:31) at com.scy.money.model.AppCrashHandler$1.run(AppCrashHandler.java:73) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.scy.money.R$layout" on path: DexPathList[[zip file "/data/app/demo.test.thirdpartapkusingaar-2/base.apk"],nativeLibraryDirectories=[/data/app/demo.test.thirdpartapkusingaar-2/lib/arm64, /system/lib64, /vendor/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:380) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) ... 3 more`
> 
> Anyone knows where the problem are?
> Thanks in advance.

Did you use reflection?
If you use reflection, you should keep your ToastUtil  construction method.

**Comment by lianbing1234** [comment]
I have the some problem, I find no R.class in the aar if setting don't warn the warming
